runtime: php
env: standard
runtime_config:
  document_root: public

# Especifica la versión de PHP que deseas utilizar
php:
  runtime: php80

handlers:
- url: /
  script: index.php
# Serve images as static resources.
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true
# Serve php scripts.
- url: /(.+\.php)$
  script: auto


  
  
  